[package]
name = "jack-compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.53"
lalrpop-util = { version = "0.22.2", features = ["lexer"] }
logos = "0.16.0"
xml = "1.2.0"

[build-dependencies]
lalrpop = "0.22.2"
